### ISSUE TITLE
BPExamplesMorph annotation is nil on new installations

### ISSUE THREAD

**Issue by ekrebs5** [hpi-swa-lab/babylonian-programming-smalltalk#140]
After installing Babylonian on Squeak 6.0, adding an example causes a MessageNotUnderstood (because the annotation of the BPExamplesMorph is nil). However, the example is still created and can be used after reloading the browser

```
Metacello new
  baseline: 'BabylonianProgramming';
  repository: 'github://hpi-swa-lab/babylonian-programming-smalltalk:develop/packages';
  load.
```

**Comment by codeZeilen** [comment]
@ekrebs5 Is that still happening? On a fresh SmalltalkCI installation I was not able to reproduce this issue.

**Comment by ekrebs5** [comment]
Does not happen in the Babylonian image I set up today, so looks good to me
