### ISSUE TITLE
Grammar misinterprets comments as by annotations

### ISSUE THREAD

**Issue by codeZeilen** [hpi-swa-lab/babylonian-programming-smalltalk#59]
BPExtractAnnotations fails for (AdditionalMethodState >> #keysAndValuesDo:) bpAnnotations with "MessageNotUnderstood: UndefinedObject>>ruleName", bc of comments such as "<Association|Pragma>". The grammar should be more strict and not try to parse these as babylonian annotations.
Reported by @LinqLover

**Comment by LinqLover** [comment]
Probably for a similar reason, the following does not compile:

```smalltalk
startTag
	^ '"<bpAnnotation id: {1} expression: [{2}]>"' format: {self id. self expression}
```

Even worse, I'm getting an infinite loop of the parser here. :-)

**Comment by LinqLover** [comment]
Thank you for the fix, but the example from above still causes an infinite loop 😝
